Vagrant.configure("2") do |config|
config.vm.box = "centos/8"
config.vm.box_check_update = false
config.vm.hostname = "r7office"
## Forwarded port from NAT
#config.vm.network "forwarded_port", guest: 80, host: 80
#config.vm.network "forwarded_port", guest: 443, host: 443
config.vm.network "public_network"
config.vm.define "centos_r7office"
## Mount folder "data" to VM "/var/www/html" 
#config.vm.synced_folder "r7-office/log", "/var/log/r7-office"
#config.vm.synced_folder "r7-office/Data", "/var/www/r7-office/Data"
config.vm.provider "virtualbox" do |vb|
vb.memory = 4092
vb.cpus = 4
end
config.vm.provision "shell", inline: <<-SHELL
hostnamectl set-hostname r7office
yum check-update
yum -y install glibc-locale-source glibc-langpack-en glibc-langpack-ru curl nano wget firewalld
localedef -f UTF-8 -i en_US en_US.utf-8
systemctl enable --now firewalld
firewall-cmd --permanent --zone=public --add-port=22/tcp
yum -y install kernel kernel-core kernel-modules bash centos-linux-release openssh openssh-clients openssh-server sudo yum yum-utils
wget https://download.r7-office.ru/repo/install-RedHat.sh
bash install-RedHat.sh
firewall-cmd --reload
ip a | grep -i -w inet
SHELL
end
