Vagrant.configure("2") do |config|
config.vm.box = "BaseALT/alt-server-9.1-amd64"
config.vm.box_check_update = false
config.vm.hostname = "r7office" 
config.vm.network "forwarded_port", guest: 80, host: 8080
config.vm.define "altserver_r7office"
config.vm.provider "virtualbox" do |vb|
vb.memory = "1024"
vb.cpus = 4
end
config.vm.provision "shell", inline: <<-SHELL
apt-get update
apt-get -y remove httpd alterator-fbi
apt-get -y remove apache2 mysql-server
apt-get install -y curl nano wget
wget https://download.r7-office.ru/repo/install-ALTLinux.sh
bash install-ALTLinux.sh
ip a | grep -i -w inet
SHELL
end
